name: Telegram Test

on:
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          --data-urlencode text="سلام زیبا 🌱 این اولین پیام آزمایشی Mini Coaching توست. سیستم با موفقیت وصل شد."
